### ISSUE TITLE
Create new tag to solve deprecation warning

### ISSUE THREAD

**Issue by evertharmeling** [freshheads/FHWebpackBundle#7]
```The "Symfony\Component\Config\Definition\Builder\TreeBuilder::root()" method called for the "fh_webpack" configuration is deprecated since Symfony 4.3, pass the root name to the constructor instead.```

This has been [fixed](https://github.com/freshheads/FHWebpackBundle/commit/8b5c324a0693aa35a17b78d25cb30a42c9a54a67), but there is no new tag to make use of the deprecation fix.

**Comment by jvandesande** [comment]
Done!
https://github.com/freshheads/FHWebpackBundle/releases/tag/1.2.1
